"""added added_by field

Revision ID: b4ccde5edf21
Revises: 
Create Date: 2023-10-02 18:37:12.297479

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b4ccde5edf21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(length=255), nullable=False),
    sa.Column('short', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
